In [5]:
import numpy as np

# Numpy Array

In [6]:
list=[1,2,3]
list

[1, 2, 3]

In [7]:
type(list)

list

In [ ]:
array=np.array(list)
array=[[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]

In [10]:
matrix_2=np.arange(5,50,5).reshape(3,3)

In [12]:
matrix_2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Random

In [17]:
np.random.rand(5)

array([0.43457552, 0.51443434, 0.6181349 , 0.44580933, 0.27944201])

In [18]:
np.random.randn(4,4)

array([[-2.29636045,  0.58099171, -0.40169051,  0.72112684],
       [ 0.43326526,  0.55168869, -1.1313686 ,  1.96194971],
       [ 0.24477827, -0.57855934,  0.5718447 ,  0.8128483 ],
       [-0.67875062,  1.55412431,  0.0925862 , -0.3471431 ]])

In [19]:
np.random.randint(0,2)

1

In [20]:
np.random.randint(100,1000,5)

array([852, 888, 552, 663, 632])

In [21]:
np.random.seed(99)
np.random.rand(4)

array([0.67227856, 0.4880784 , 0.82549517, 0.03144639])

In [22]:
np.random.rand(4)

array([0.80804996, 0.56561742, 0.2976225 , 0.04669572])

# Mx-Min

In [25]:
np.random.seed(99)
random=np.random.randint(0,100,15)
random

array([ 1, 35, 57, 40, 73, 82, 68, 69, 52,  1, 23, 35, 55, 65, 48])

In [26]:
random.max

<function ndarray.max>

In [27]:
random.max()

82

In [34]:
random.argmax()

5

 # Shape & Type

In [35]:
array
array

[[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]]